### ISSUE TITLE
Error creating CSRF code 

### ISSUE THREAD

**Issue by SaphiLC** [ikkez/f3-flash#1]
i have this code in my base controller's afterroute:
$flash = Flash::instance()->getMessages();
$flash ? $f3->set('FLASH', $flash) : $f3->set('FLASH', 'empty');

and when i try to generate a CSRF code with:
(i have cache on)
$s = new Session();
$f3->CSRF = $s->csrf();

i get this error: (if i comment the 1st code that instances flash, then no error)
session_start(): Failed to read session data: user (path: E:/laragon/tmp)
[E:/laragon/www/base/vendor/bcosca/fatfree-core/base.php:2152] Base->error()
[E:/laragon/www/base/vendor/bcosca/fatfree-core/base.php:273] session_start()
[E:/laragon/www/base/app/inc/Flash.php:31] Base->ref()
[E:/laragon/www/base/vendor/bcosca/fatfree-core/base.php:35] Flash->__construct()
[E:/laragon/www/base/app/controller/BaseController.php:9] Prefab::instance()
[E:/laragon/www/base/vendor/bcosca/fatfree-core/base.php:1782] BaseController->afterroute()
[E:/laragon/www/base/vendor/bcosca/fatfree-core/base.php:1599] Base->call()
[E:/laragon/www/base/public/index.php:32] Base->run()

**Comment by ikkez** [comment]
This is probably no problem with the flash plugin, as your error is "Failed to read session data: **user**" within a template. Make sure you have your the database session initialized before you use the SESSION anywhere. (i.e. put `new Session()` into index.php )

**Comment by SaphiLC** [comment]
i do have the  "new session()" on index.php :(

and made my own "flashing" code and gives the same error :( so not sure whats going on :(

**Comment by ikkez** [comment]
I did a quick search and came to this one: http://stackoverflow.com/questions/41540302/failed-to-read-session-data-on-php7-1
so it's maybe just a php 7.x and fat-free issue. The latest dev version for fat-free has some php7 fixes included, which should solve your issue. get https://github.com/bcosca/fatfree-core
