### ISSUE TITLE
How to close the flash message?

### ISSUE THREAD

**Issue by fralbo** [ikkez/f3-flash#3]
Hello,
Sorry it's more question than an issue I suppose but I would ilke to know what to do to close the Flash Message because the button doesn't do anything.

Regards,
Alain

**Comment by richgoldmd** [comment]
The sample html code depends on the bootstrap library, and with bootstrap loaded the proposed html dismissed the message when the close button is checked. 

This library itself doesn’t do anything specific with regards to display. It’s up to you to add the necessary html and/JavaScript to get that behavior.
